name: market-data-collector

services:
  postgres:
    image: postgres:18.6
    container_name: market-data
    restart: unless-stopped

    environment:
      POSTGRES_DB: market_data
      POSTGRES_USER: arasaka
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data: